name: Set up Istio

on:
  push:
    branches:
    - main

env:
  PPROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER1: dev-gke
  GKE_CLUSTER2: qa-gke
  GKE_CLUSTER3: prod-gke
  GKE_ZONE: us-central1-a

jobs:
  Job1:
    name: Setup Dev Istio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    #- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER1" --zone "$GKE_ZONE"
        
   
   # Set up istio
    - name: Set up Istio
      run: |-
       curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.3 sh -
       cd istio-1.7.3
       export PATH=$PWD/bin:$PATH
       istioctl install --set profile=demo
       cd ~
       #kubectl label namespace default istio-injection=enabled 
       kubectl label namespace default istio-injection=enabled --overwrite
       
       
  Job2:
    name: Setup QA Istio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER2" --zone "$GKE_ZONE"
        
   
   # Set up istio
    - name: Set up Istio
      run: |-
       curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.3 sh -
       cd istio-1.7.3
       export PATH=$PWD/bin:$PATH
       istioctl install --set profile=demo
       cd ~
       #kubectl label namespace default istio-injection=enabled 
       kubectl label namespace default istio-injection=enabled --overwrite   
       
       
  Job3:
    name: Setup PROD Istio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER3" --zone "$GKE_ZONE"
        
   
   # Set up istio
    - name: Set up Istio
      run: |-
       curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.3 sh -
       cd istio-1.7.3
       export PATH=$PWD/bin:$PATH
       istioctl install --set profile=demo
       cd ~
       #kubectl label namespace default istio-injection=enabled 
       kubectl label namespace default istio-injection=enabled --overwrite     
